#!/usr/bin/python3
# -*- coding: utf-8 -*-

# text colours
COLOUR_WHITE_FG = '\033[97m'
COLOUR_LIGHT_FG = '\033[38;5;250m'
COLOUR_YELLOW_FG = '\033[33;40m'
COLOUR_GREEN_FG = '\033[32;40m'
COLOUR_RED_FG = '\033[31;40m'
COLOUR_GREY_FG = '\033[38;5;246m'
COLOUR_ORANGE_FG = '\033[38;5;214m'

# background colours
COLOUR_DARK_GREY_BG = '\033[48;5;234m'

# colour modifiers
COLOUR_BOLD = '\033[1m'
COLOUR_RESET = '\033[0m'

# colour scheme
COLOURS_MENU_BOX = COLOUR_LIGHT_FG + COLOUR_DARK_GREY_BG
COLOURS_MENU_TITLE_REGULAR = COLOUR_ORANGE_FG + COLOUR_BOLD + COLOUR_DARK_GREY_BG
COLOURS_MENU_TITLE_SPECIAL = COLOUR_YELLOW_FG + COLOUR_BOLD + COLOUR_DARK_GREY_BG
COLOURS_MENU_ITEM = COLOUR_LIGHT_FG + COLOUR_DARK_GREY_BG
COLOURS_SINGLE_ENTRY_BOX = COLOUR_GREY_FG + COLOUR_DARK_GREY_BG
COLOURS_SINGLE_ENTRY_TITLE = COLOUR_WHITE_FG + COLOUR_BOLD + COLOUR_DARK_GREY_BG
COLOURS_SINGLE_ENTRY_HEADER = COLOUR_GREY_FG + COLOUR_DARK_GREY_BG
COLOURS_SINGLE_ENTRY_NAME = COLOUR_LIGHT_FG + COLOUR_DARK_GREY_BG
COLOURS_SINGLE_ENTRY_VALUE = COLOUR_ORANGE_FG + COLOUR_DARK_GREY_BG
COLOURS_PROMPT = COLOUR_LIGHT_FG + COLOUR_BOLD
COLOURS_ALLOWED_ITEM_KEY = COLOUR_ORANGE_FG + COLOUR_BOLD + COLOUR_DARK_GREY_BG
COLOURS_ALLOWED_OPTION_KEY = COLOUR_YELLOW_FG + COLOUR_BOLD + COLOUR_DARK_GREY_BG
COLOURS_FAVORITE_STAR = COLOUR_YELLOW_FG + COLOUR_BOLD + COLOUR_DARK_GREY_BG
COLOURS_WRITE_OK = COLOUR_GREEN_FG + COLOUR_BOLD
COLOURS_WRITE_FAIL = COLOUR_RED_FG + COLOUR_BOLD
